---
- name: Add ppa for php 5.6
  apt_repository: repo="ppa:ondrej/php5-5.6"

- name: Install php 5.6 and extensions
  apt: name={{item}}
  with_items:
    - php5
    - php5-mysql
    - php-apc
    - php5-gd
    - sendmail

- name: Copy php.ini
  template: src=etc-php5-apache2-php.ini.j2 dest=/etc/php5/apache2/php.ini

- name: Enable pdo extension
  command: php5enmod pdo